version: 2
jobs:
  build:
      - checkout
      - run:
          name: build
          command: mvn package
      - persist_to_workspace:
          root: target
          paths: deployment
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Authorize GCloud Command Line Tool
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode | gcloud auth activate-service-account --key-file=-
      - run:
          name: Deploy To Google Cloud Functions
          command: |
            # Variables
            # Deploy command
            gcloud functions deploy $FUNCTION_NAME \
              --entry-point=io.quarkus.gcp.functions.QuarkusBackgroundFunction \
              --runtime java11 \
              --trigger-event google.pubsub.topic.publish \
              --source=/tmp/workspace/deployment \
              --project $GCP_PROJECT \
              --trigger-resource test
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
