version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.7-jdk-buster
    steps:
      - checkout
      - run:
          name: build
          command: mvn package
      - persist_to_workspace:
          root: target
          paths: deployment
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Authorize GCloud Command Line Tool
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode | gcloud auth activate-service-account $GCP_ACCOUNT --key-file=-
      - run:
          name: Deploy To Google Cloud Functions
          command: |
            # Variables
            # Deploy command
            gcloud beta functions deploy quarkus-example-pubsub \
              --entry-point=io.quarkus.gcp.functions.QuarkusBackgroundFunction \
              --runtime=java11 --trigger-resource hello_topic --trigger-event google.pubsub.topic.publish --source=/tmp/workspace/deployment

            gcloud functions deploy scrapeFunction \
              --entry-point=io.quarkus.gcp.functions.QuarkusBackgroundFunction \
              --runtime java11 \
              --trigger-event google.pubsub.topic.publish \
              --source=/tmp/workspace/deployment \
              --project $GCP_PROJECT \
              --trigger-resource test
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
